# Generated by Django 6.0.7 on 2026-07-11 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pavimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Pavimento',
                'verbose_name_plural': 'Pavimentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pilar', 'Pilar'), ('sapata', 'Sapata'), ('viga', 'Viga')], max_length=10, verbose_name='Tipo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do tipo')),
                ('identificador', models.CharField(max_length=50, verbose_name='ID')),
                ('qtde', models.PositiveIntegerField(verbose_name='QTDE')),
                ('diametro', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='DIAM (mm)')),
                ('comprimento', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='L (m)')),
                ('peso_linear', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Peso linear (kg/m)')),
                ('peso_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Peso total (kg)')),
                ('peso_unitario', models.DecimalField(decimal_places=3, editable=False, max_digits=12, verbose_name='Peso unit. PÇ (kg)')),
                ('pavimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='core.pavimento', verbose_name='Pavimento')),
            ],
            options={
                'verbose_name': 'Elemento',
                'verbose_name_plural': 'Elementos',
                'ordering': ['tipo', 'nome', 'identificador'],
            },
        ),
    ]
