# Generated by Django 6.0.7 on 2026-07-12 15:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_elemento_diametro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='diametro',
            field=models.DecimalField(choices=[(Decimal('5.0'), '5,0'), (Decimal('6.3'), '6,3'), (Decimal('8.0'), '8,0'), (Decimal('10.0'), '10'), (Decimal('12.5'), '12,5'), (Decimal('16.0'), '16'), (Decimal('20.0'), '20')], decimal_places=1, max_digits=5, verbose_name='DIAM (mm)'),
        ),
    ]
