# Generated by Django 6.0.7 on 2026-07-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_elemento_diametro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='tipo',
            field=models.CharField(choices=[('pilar', 'Pilar'), ('sapata', 'Sapata'), ('viga', 'Viga'), ('estaca', 'Estaca')], max_length=10, verbose_name='Tipo'),
        ),
    ]
