# Generated by Django 5.2.15 on 2026-07-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_elemento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='tipo',
            field=models.CharField(choices=[('pilar', 'Pilar'), ('sapata', 'Sapata'), ('viga', 'Viga'), ('estaca', 'Estaca'), ('piso_estr_x', 'Piso estruturado X'), ('piso_estr_y', 'Piso estruturado eixo Y')], max_length=20, verbose_name='Tipo'),
        ),
    ]
