# Generated by Django 6.0.7 on 2026-07-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_elemento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='tipo',
            field=models.CharField(choices=[('pilar', 'Pilar'), ('sapata', 'Sapata'), ('viga', 'Viga'), ('estaca', 'Estaca'), ('laje', 'Laje')], max_length=20, verbose_name='Tipo'),
        ),
    ]
