# Generated by Django 6.0.7 on 2026-07-14 18:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_elemento_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elemento',
            options={'ordering': ['categoria', 'tipo', 'nome', 'identificador'], 'verbose_name': 'Elemento', 'verbose_name_plural': 'Elementos'},
        ),
        migrations.AddField(
            model_name='elemento',
            name='categoria',
            field=models.CharField(choices=[('aco', 'Aço'), ('forma', 'Forma'), ('concreto', 'Concreto')], default='aco', max_length=20, verbose_name='Elemento'),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='comprimento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='L (m)'),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='diametro',
            field=models.DecimalField(blank=True, choices=[(Decimal('5.0'), '5,0'), (Decimal('6.3'), '6,3'), (Decimal('8.0'), '8,0'), (Decimal('10.0'), '10'), (Decimal('12.5'), '12,5'), (Decimal('16.0'), '16'), (Decimal('20.0'), '20')], decimal_places=1, max_digits=5, null=True, verbose_name='DIAM (mm)'),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='peso_linear',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Peso linear (kg/m)'),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='peso_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12, verbose_name='Peso total (kg)'),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='peso_unitario',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=12, verbose_name='Peso unit. PC (kg)'),
        ),
    ]
