# Generated by Django 6.0.7 on 2026-07-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_elemento_options_elemento_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='medida',
            field=models.CharField(blank=True, max_length=100, verbose_name='Medida'),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='identificador',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='qtde',
            field=models.PositiveIntegerField(default=1, verbose_name='QTDE'),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='tipo',
            field=models.CharField(blank=True, choices=[('pilar', 'Pilar'), ('sapata', 'Sapata'), ('viga', 'Viga'), ('estaca', 'Estaca'), ('laje', 'Laje')], max_length=20, verbose_name='Tipo'),
        ),
    ]
