# Generated by Django 6.0.7 on 2026-07-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_elemento_medida_alter_elemento_identificador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='medida',
            field=models.CharField(blank=True, max_length=100, verbose_name='Medida (m)'),
        ),
    ]
