# Generated by Django 6.0.7 on 2026-07-15 13:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_elemento_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='medida_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Medida 1 (m)'),
        ),
        migrations.AddField(
            model_name='elemento',
            name='medida_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Medida 2 (m)'),
        ),
        migrations.AddField(
            model_name='elemento',
            name='volume',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=12, verbose_name='Volume (m³)'),
        ),
    ]
